/*
 * do not edit this file directly - as it will get updated automatically width MightyEditor update
 */

(function(){
	"use strict";
	
	Phaser.TilemapLayer.prototype.getTileX = function (x) {

		// var tileWidth = this.tileWidth * this.scale.x;
		return Math.floor(x / this._mc.tileWidth);

	};
	Phaser.TilemapLayer.prototype.getTileY = function (y) {

		// var tileWidth = this.tileWidth * this.scale.x;
		return Math.floor(y / this._mc.tileHeight);

	};
})();
